# Generated by Django 4.2.5 on 2023-10-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('escudo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('posicion', models.CharField(max_length=40)),
                ('equipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.IntegerField()),
                ('equipo_Local', models.CharField(max_length=40)),
                ('equipo_visitante', models.CharField(max_length=40)),
                ('goles_local', models.IntegerField()),
                ('goles_visitante', models.IntegerField()),
            ],
        ),
    ]
